## LANGUAGE
defaultContentLanguage: fr
baseURL: https://tomgue.github.io/

## ADVANCED
build:
  buildStats:
    disableClasses: false
    disableIDs: true
    disableTags: false
    enable: true
enableRobotsTXT: true
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 9
removePathAccents: true
