## LANGUAGE
defaultContentLanguage: fr
enableEmoji: true
enableRobotsTXT: true

markup:
  highlight:
    style: nord
  goldmark:
    extensions:
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: false
