## LANGUAGE
defaultContentLanguage: fr
enableEmoji: true
enableRobotsTXT: true

markup:
  goldmark:
    extensions:
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: false
