_merge: deep

# Admin
admin:
  cms: sveltiacms
  name: github
  repo: tomgue/tomgue.github.io
  netlify:
    identity: false
  collections:
    docs:
      depth: 10
      summary: '{{title}}'
      subfolders: true
    meta: { path: { index_file: _index } }
    indexes:
      enable: false
