_merge: deep

# logo:
#   header: '/assets/images/logo.svg'
#   footer: '/assets/images/logo-footer.svg' # default: /assets/images/logo.svg

image:
  retina:
    desktop: true # default false, Set true to enable retina for desktop

css:
  darkmode: true
  preload: true
  print: true
  postcss: 'postcss/design-system'

# Search
search:
  enable: true # Set true to enable search
  layout: drawer # Also raw, modal or drawer
  filter: false # Set true to add filters by type
  sort: true

# Admin
admin:
  cms: sveltiacms
  name: github
  repo: tomgue/tomgue.github.io
  title: TomLab CMS
  netlify:
    identity: false
  collections:
    pages:
      media_folder: '{{media_folder}}/pages'
      public_folder: '{{public_folder}}/pages'
      summary: "**{{title}}** - {{draft | ternary('⛔️ Brouillon', '✅ _Publié_')}}"
    docs:
      thumbnail: image.src
      summary: "**{{title}}** - {{draft | ternary('⛔️ Brouillon', '✅ _Publié_')}}"
      nested:
        depth: 10
        subfolders: true
    indexes:
      enable: false
